### PR TITLE
make RtpPacket::SharedPtr

### PR DESCRIPTION
**Pull request by satoren**
Create smartpointer class for RTC::RtpPacket. Because when using std::shared_ptr that need extra allocation cost for count and pointer area.

### CODE REVIEW

**Comment by nazar-pc** [comment]
Thanks, I'll take a look when I have time

**Review by nazar-pc — APPROVED** [review]
I wish C++ syntax wasn't as confusing...

Thanks for these changes!
They make sense to me and CI passes, so I'll merge it.

**Comment by nazar-pc** [comment]
@satoren these changes cause mediasoup to leak memory continuously, can you check it, please?

UPD: Fixed myself

**Comment by satoren** [comment]
Very thank you for the memory leak fix.

**Pull request merged**
